[package]
name = "noisefog"
version = "0.1.0"
edition = "2021"


[dependencies]
wasm-bindgen = "0.2"
noise = "0.6.0"
image = "0.22.2"
lerp = "0.2.0"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }