[package]
name = "noisefog"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2"
noise = "0.6.0"
image = "0.24.8"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }